// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnabs321oxgkVxRUPpLfLUDIG1qVJBkWs',
    appId: '1:96046852438:web:04f36907be14c9af264ef7',
    messagingSenderId: '96046852438',
    projectId: 'sldm-tracking-app',
    authDomain: 'sldm-tracking-app.firebaseapp.com',
    storageBucket: 'sldm-tracking-app.firebasestorage.app',
    measurementId: 'G-YVWNYM45K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE7gKAVjDufr8QvBbxr0Ot5vP5W8_PXww',
    appId: '1:96046852438:android:3db8604e7b1e498a264ef7',
    messagingSenderId: '96046852438',
    projectId: 'sldm-tracking-app',
    storageBucket: 'sldm-tracking-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKWMp1C2laRi9kViZCJUvI8KUPTJj9oR4',
    appId: '1:96046852438:ios:c4897d61fbbb8c1d264ef7',
    messagingSenderId: '96046852438',
    projectId: 'sldm-tracking-app',
    storageBucket: 'sldm-tracking-app.firebasestorage.app',
    iosBundleId: 'app.sldm.sldmtrackingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKWMp1C2laRi9kViZCJUvI8KUPTJj9oR4',
    appId: '1:96046852438:ios:c4897d61fbbb8c1d264ef7',
    messagingSenderId: '96046852438',
    projectId: 'sldm-tracking-app',
    storageBucket: 'sldm-tracking-app.firebasestorage.app',
    iosBundleId: 'app.sldm.sldmtrackingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnabs321oxgkVxRUPpLfLUDIG1qVJBkWs',
    appId: '1:96046852438:web:b5f76fa3465c2d5a264ef7',
    messagingSenderId: '96046852438',
    projectId: 'sldm-tracking-app',
    authDomain: 'sldm-tracking-app.firebaseapp.com',
    storageBucket: 'sldm-tracking-app.firebasestorage.app',
    measurementId: 'G-C2W6QLGLQ2',
  );
}
